version: 2.1

orbs:
  planeat: alimentiamoci/planeat-app-orb@0.2.4

only-release-tags: &only-release-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /.*/

fingerprint: &fingerprint
  fingerprint: "SHA256:uZmd4PjO/74dET53wPDnVr1lV2bw9C+acbomNjoQ614"

workflows:
  publish:
    jobs:
      - planeat/notify_start:
          <<: *only-release-tags
          context:
            - slack
      - planeat/publish:
          <<: *only-release-tags
          <<: *fingerprint
          context:
            - slack
            - onepub
          requires:
            - planeat/notify_start
